# Generated by Django 4.2.6 on 2023-10-31 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_data', '0002_user_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TwitterUser',
        ),
    ]
